version: '3.4'

services:
  app1:
    image: app1
    build:
      context: .
      dockerfile: App1/Dockerfile
     


  app2:
    image: app2
    build:
      context: .
      dockerfile: App2/Dockerfile
    


