version: '3.4'

services:
  app1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5505:80" 
    networks:
      - network
    links:
      - app2
  app2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5506:80" 
    networks:
      - network

networks: 
    network:
        driver: bridge    

