version: '3'

services:
  app1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5505:80"

  app2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5506:80"

